const About = () => {
  return (
    <div>
        <h1 className='bg-gray-600 p-4 text-white'>Home</h1>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem enim quia est, pariatur eligendi error accusamus impedit necessitatibus excepturi aut dolor praesentium, dolores consequatur obcaecati eos sequi. Esse libero nisi molestias repudiandae dolore sint aliquid consequuntur labore asperiores incidunt. Debitis totam ducimus illum ab maxime libero itaque, eaque suscipit eveniet aperiam odit, dolores, voluptatem at soluta excepturi molestiae aliquid quia.
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatibus repudiandae, unde ex architecto, eius obcaecati impedit nihil doloribus modi sapiente ab fugiat. Atque, vero similique doloribus nemo dolorum nesciunt, exercitationem, placeat autem temporibus voluptatem cumque officiis maiores voluptatum sed optio? Aspernatur consectetur animi et? Quod, non soluta! Placeat, facere. Maiores reprehenderit dicta quas nihil recusandae illo voluptas quisquam praesentium nisi a maxime minus error ipsam quod accusamus deserunt excepturi quia, asperiores similique rem? Sunt nihil iusto quisquam quo dolore. Et optio perferendis dolores repellendus ullam fugiat ea inventore reiciendis fuga numquam sit maiores, molestiae deleniti recusandae animi enim facilis voluptatibus distinctio fugit, nam ipsam aspernatur exercitationem, impedit asperiores? Ipsam maiores, id unde temporibus, aperiam delectus sunt dolores reiciendis velit magnam voluptatibus eveniet! Ipsam doloremque perferendis consectetur ad reiciendis, similique molestiae velit sint facilis fugit laudantium veritatis, pariatur iste exercitationem at! Ex asperiores esse animi, at accusamus, earum doloremque eos, odit eaque eum ab vitae? Perferendis repellat cupiditate facere laboriosam itaque maxime libero totam impedit magnam dolor non animi praesentium labore ea laudantium, nobis possimus? Voluptas placeat eaque, nulla ea, culpa optio rerum quos aliquam laborum atque itaque autem debitis, saepe odit hic pariatur praesentium dignissimos ratione. Veniam expedita quae veritatis consequuntur in. Nobis provident qui ad necessitatibus aut dolores temporibus maiores animi distinctio velit. Sequi, saepe eaque. Enim voluptate veniam voluptas! Eos facilis eaque libero fugit, itaque vero possimus commodi iure. Ipsum magnam necessitatibus, maxime distinctio deleniti iusto placeat adipisci nesciunt veritatis dolorum repudiandae deserunt modi eveniet id reiciendis incidunt consectetur? Veritatis laborum, incidunt beatae quaerat officia culpa porro ratione iste laudantium ipsum fuga? Possimus deserunt, accusantium veniam, quas laborum accusamus vel velit excepturi quae illum natus debitis id? Asperiores, obcaecati. Aperiam eius fugiat non minima molestiae neque possimus. Laboriosam fugiat ducimus provident, facilis molestiae impedit non distinctio quos magnam.
    </div>
  )
}

export default About